client_config_backend: settings
client_config:
  client_id: COLOQUE_AQUI_SEU_CLIENT_ID
  client_secret: COLOQUE_AQUI_SEU_CLIENT_SECRET

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install
